# Numpy , Pandas and Matplotlib 

**Numpy**

**bold text**

1. Create a 1D array of numbers from 0 to 9. 




In [5]:
import numpy as np
arr = np.arange(0,10)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**2.Create a 3×3 numpy array of all True’s**

In [9]:
np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

**3.Extract all odd numbers from arr**
 
 **Input:**
 arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.where(arr%2 != 0)

(array([1, 3, 5, 7, 9]),)

**4.Replace all odd numbers in arr with -1 without changing arr**


**Input:**
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr = np.arange(10)
out = np.where(arr % 2 == 1,-1,arr)
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

**5.Convert the function maxx that works on two scalars, to work on two arrays.**

In [16]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx)
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)



array([6, 7, 9, 8, 9, 7, 5])

**6.  Pretty print rand_arr by suppressing the scientific notation (like 1e10)**

In [20]:
# Reset printoptions to default
np.set_printoptions(suppress=False)

# Create the random array
np.random.seed(100)
rand_arr = np.random.random([2,3])
print(rand_arr)
#write code for precision is 6
np.set_printoptions(precision=6)
print(rand_arr)

[[0.54340494 0.27836939 0.42451759]
 [0.84477613 0.00471886 0.12156912]]
[[0.543405 0.278369 0.424518]
 [0.844776 0.004719 0.121569]]


**7.Convert the 1D iris to 2D array iris_2d by omitting the species text field.**

In [ ]:
# Input:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)


# Method 1: Convert each row to a list and get the first 4 items
iris_2d = np.array(#your code here)

print(iris_2d[:4])
# Alt Method 2: Import only the first 4 columns from source url
iris_2d = np.genfromtxt(#your code here)
print(iris_2d[:4])

**8.Compute the softmax score of sepallength.**

In [ ]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.array([float(row[0]) for row in iris])

# Solution
def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    #your code here
     return e_x / e_x.sum(axis=0)

print(softmax(sepallength)

**9.Randomly sample iris's species such that setose is twice the number of versicolor and virginica**


In [ ]:
# Import iris keeping the text column intact
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

# Solution
# Get the species column
species = iris[:, 4]

# Approach 1: Generate Probablistically
np.random.seed(100)
a = np.array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'])
species_out = #your code here

# Approach 2: Probablistic Sampling (preferred)
np.random.seed(100)
probs = np.r_[np.linspace(0, 0.500, num=50), np.linspace(0.501, .750, num=50), np.linspace(.751, 1.0, num=50)]
index = #your code here
species_out = species[index]
print(np.unique(species_out, return_counts=True))


**10.Compute the one-hot encodings (dummy binary variables for each unique value in the array)**

In [30]:

np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
print(arr)
def one_hot_encodings(arr):
    uniqs = np.unique(arr)
    out = np.zeros((arr.shape[0], uniqs.shape[0]))
    for i, k in enumerate(arr):
      # print(i,k)
      # out[i,k-1]=1
    return out

one_hot_encodings(arr)


[2 3 2 2 2 1]
0 2
1 3
2 2
3 2
4 2
5 1


array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])